schema = 1
package_name = "radeon-unified-dkms-dev"
package_version = "0.8.3"
package_release = 1
source_repository = "Oichkatzelesfrettschen/linux-radeon-gororoba"
source_commit = "74cc62c478bd11778ae398d6d1e5f5f43a12fa7a"
repository_tree = "1c431728eed8df1bd9acf1fce32961e195d8d9a7"
driver_tree = "4d5217ea558320801dde0ef8ce2d8ffdb7a21ba9"
build_profile = "all-dev"
compiled_ceiling = "mutate-dev"
feature_policy_sha256 = "0b13f129dfbea582abee481f5078c748ad489f65a7aab9a1c5dc428055e62424"
upstream_base = "7d0a66e4bb9081d75c82ec4957c50034cb0ea449"
kernel_build_interface = 1
