schema = 1
package_name = "radeon-unified-dkms-dev"
package_version = "0.8.2"
package_release = 1
source_repository = "Oichkatzelesfrettschen/linux-radeon-gororoba"
source_commit = "6407ae6ee1bdd23d64c0657cced20d3a03226b06"
repository_tree = "5834b81e6a6e8d62b1dbda964f6e0e0af2d239ff"
driver_tree = "6f3e3d2e4aec146aa6cd491416668ee096b94bb8"
build_profile = "all-dev"
compiled_ceiling = "mutate-dev"
feature_policy_sha256 = "0b13f129dfbea582abee481f5078c748ad489f65a7aab9a1c5dc428055e62424"
upstream_base = "7d0a66e4bb9081d75c82ec4957c50034cb0ea449"
kernel_build_interface = 1
